name: Python tests (Pixi)

concurrency:
  group: pixi-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false

    - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
      with:
        pixi-version: v0.69.0
        locked: true
        cache: true
        cache-write: ${{ github.ref == 'refs/heads/main' }}
        environments: dev

    - run: |
        pixi reinstall -e dev NLR-GAPs
        pixi run -e dev tests
