name: reV CLI Tests

concurrency:
  group: rev-cli-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on: pull_request

jobs:
  rev_cli_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: checkout gaps
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
        fetch-tags: true
        path: gaps
        persist-credentials: false
    - name: checkout reV
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: NatLabRockies/reV
        fetch-depth: 1
        path: reV
        fetch-tags: true
        persist-credentials: false
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        auto-update-conda: true
        python-version: 3.13
    - name: Install reV
      working-directory: ./reV
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Install gaps
      working-directory: ./gaps
      shell: bash -l {0}
      run: |
        pip install -e .[dev,test]
    - name: Run reV CLI tests
      working-directory: ./reV
      shell: bash -l {0}
      run: |
        pytest -k cli -v --disable-warnings
